// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `pad_to_32`

/// 生成 SM2 密钥对，返回 Base64 编码的公钥和私钥。
///
/// 返回值：
/// - 第一个元素为公钥的 Base64 编码字符串（包含 0x04 前缀的 65 字节未压缩格式）
/// - 第二个元素为私钥的 Base64 编码字符串（32 字节大端格式）
Future<(String, String)> genSm2Key() =>
    RustLib.instance.api.crateApiSm2KeyGeneratorGenSm2Key();

/// 根据私钥生成 SM2 公钥，返回 Base64 编码的公钥
Future<String> sm2PkFromSk({required String skBase64}) =>
    RustLib.instance.api.crateApiSm2KeyGeneratorSm2PkFromSk(skBase64: skBase64);
