name: Build Flutter Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x64, arm64 ]
        exclude:
          - arch: arm64
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.3'

      - name: Setup Linux Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libgtk-3-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Cargo Expand
        run: cargo install cargo-expand

      - name: Get Dependencies
        run: flutter pub get

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Install Flutter Rust Bridge Codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Generate Rust Bindings
        run: flutter_rust_bridge_codegen generate

      - name: Build Linux (Release)
        run: flutter build linux --release --target-platform=linux-${{ matrix.arch }}

      - name: Package Linux Artifact
        run: |
          cd build/linux/${{ matrix.arch }}/release/bundle/
          tar -czf ../flutter_app_linux_${{ matrix.arch }}.tar.gz .
          mv ../flutter_app_linux_${{ matrix.arch }}.tar.gz ./

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-app-linux-${{ matrix.arch }}
          path: build/linux/${{ matrix.arch }}/release/bundle/flutter_app_linux_${{ matrix.arch }}.tar.gz